---
title: "Clustering"
author: "SorenH"
date: "`r Sys.Date()`"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---




```{r, setup, echo = FALSE, message = FALSE, warning = FALSE}
library("reticulate", quietly = TRUE, warn.conflicts = FALSE)
library("here", quietly = TRUE, warn.conflicts = FALSE)
library("glue", quietly = TRUE, warn.conflicts = FALSE)
library("ggplot2", quietly = TRUE, warn.conflicts = FALSE)
library("tidyverse", quietly = TRUE, warn.conflicts = FALSE)
library("ggbiplot", quietly = TRUE, warn.conflicts = FALSE)
library("broom")
library(ggdendro)
library("ape")
setwd(here::here())
knitr::opts_knit$set(root.dir = here::here(),
                     message = FALSE,
                     warning = FALSE,
                     echo = FALSE)
use_condaenv("py3.8", required = TRUE)
```



```{r}
query <-  "NulO_merged"

psi_id_filt <- read.delim(glue("./output/psi_percID_filt/{query}.tsv"))
psi_proxi_filt <- read.delim(glue("./output/psi_proxi_filt/{query}.tsv"))


PCA_pre_proces <-  psi_id_filt %>% 
  mutate(coverage = (end_target - start_target) / (end - start)/3,) %>%
  group_by(operon) %>% 
  dplyr::summarize(
    mean_bit = mean(Bit.score),
    mean_cov = mean(coverage),
    mean_perc_id = mean(Percent_identity),
    size = length(coverage),
    size_uniq = length(unique(Query_label)),
    repetition = size_uniq/size
    ) %>%
  merge(aggregate(Target_label ~ operon, data=psi_id_filt, head, 1), by="operon")  %>% 
  mutate(
    in_operon = case_when(
      Target_label %in% psi_proxi_filt$Target_label ~ "Proximity Filtration",
      TRUE ~ "Removed"),
    ) %>%  
  filter(size > 1 & size < 15)

PCA_model <- PCA_pre_proces %>% 
  select(mean_bit, mean_cov, mean_perc_id, size_uniq, repetition) %>% 
  prcomp(scale. = TRUE, center = TRUE)

# setting plot themes
theme_set(new = theme_bw() + theme(legend.position = "bottom"))
theme(legend.position = "bottom")
# Scree plot
summary(PCA_model)$importance %>% `[`(2,) %>% 
  data.frame(variance = .) %>% 
  mutate(PC  = row.names(.) ) %>% 
  ggplot(aes(x = PC, y = variance)) +
  geom_point() +
  xlab("Principal Component") +
  ylab("Variance explained") +
  ggtitle("Scree Plot of Principal Components")


# biplot
ggbiplot(PCA_model, choices = 1:2, groups = as.character(PCA_pre_proces$size_uniq), alpha = 0.4) + 
  ggtitle(glue("{query}")) +
  guides(color = guide_legend(title = "Nr. unique \n gene hits"))

# biplot
ggbiplot(PCA_model, choices = c(1, 3), groups = as.character(PCA_pre_proces$size_uniq), alpha = 0.4) + 
  ggtitle(glue("{query}")) +
  guides(color = guide_legend(title = "Nr. unique \n gene hits"))

# biplot
ggbiplot(PCA_model, choices = 2:3, groups = as.character(PCA_pre_proces$size_uniq), alpha = 0.4) + 
  ggtitle(glue("{query}")) +
  guides(color = guide_legend(title = "Nr. unique \n gene hits"))


# Selecting number of PC's to include in clustering
PCA_data = PCA_model$x[,c("PC1", "PC2", "PC3")]
  
# Kmeans clustering
kmeans_PCA <- kmeans(PCA_model$x, 4)
ggbiplot(PCA_model, choices = 1:2, groups = as.character(kmeans_PCA$cluster), alpha = 0.4) + 
  ggtitle(glue("{query}, colored by kmeans clustering, n = 2")) +
  guides(color = guide_legend(title = "Cluster"))
```


```{r}
# hiearical clustering
rownames(PCA_data) <- PCA_pre_proces$operon
hclust_PCA <- hclust(dist(PCA_data), method = "ward.D2") %>% 
  as.dendrogram() %>% 
  dendro_data(type = "rectangle")
hclust_PCA$labels <- hclust_PCA$labels %>% 
  mutate(operon = as.numeric (label)) %>% 
  left_join(PCA_pre_proces, by = "operon")

ggplot(segment(hclust_PCA)) + 
  geom_segment(aes(x = x, y = y, xend = xend, yend = yend)) + 
  theme_dendro() + 
  geom_text(data = label(hclust_PCA),
            aes(x = x, y = y, label = size_uniq, color = as.factor(size_uniq)), cex = 0.8)
```


```{python}
import numpy as np

from sklearn.cluster import MeanShift, estimate_bandwidth
from sklearn.datasets import make_blobs

# Importing PC1 and PC2
PCA_data = r.PCA_data
bw = estimate_bandwidth(PCA_data, quantile = 0.15, n_samples = 500)
ms = MeanShift(bandwidth = bw, bin_seeding = True)
ms.fit(PCA_data)

```



```{r}
dir.create("./figures/clustering")
PCA_data_labels <- PCA_data %>% 
  as_tibble() %>% 
  cbind(as.factor(py$ms$labels_)) %>% 
  cbind(PCA_pre_proces) %>% 
  mutate (size_uniq = as.character(size_uniq))
colnames(PCA_data_labels)[4] <- "labels"

#ggsave(filename = glue("./figures/clustering/{query}_meanshift.pdf"), device = "pdf",
ggplot(PCA_data_labels, aes(x = PC1, y = PC2, col = labels, shape = size_uniq)) +
  geom_point(aes(), alpha = 0.6) +
  scale_shape_manual(values = c(1:4, 16, 17, 18, 19)) +
  theme_bw() +
  ggtitle (glue("{query}, colored by mean shift clustering")) +
  guides(color = guide_legend(title = "Cluster"),
         shape = guide_legend(title = "Nr. of unique\n genes in operon"))
#)


```

